forgotten changes to fixWifi

diff --git a/fixWifi b/fixWifi
--- a/fixWifi
+++ b/fixWifi
@@ -23,24 +23,28 @@ connect(){
 	return $?
 }
 
-build
-for con in $CON; do
-	for dev in $DEV; do
-		if [ -z $con -o -z $dev ]; then
-			continue
-		fi
-		i=0
-		while [ $i -ne 10 ]; do
-			((i++))
-			connect $dev $con
-			exitStatus=$?
-			if [ $exitStatus -ne 0 ]; then
-				echo "FAILED, RETRYING $exitStatus"|grep --color .\*
-			else
-				echo "SUCCESS $exitStatus"|grep --color .\*
-				exit
+if ping -c 1 www.google.com >/dev/null 2>&1; then
+	echo connected
+else
+	build
+	for con in $CON; do
+		for dev in $DEV; do
+			if [ -z $con -o -z $dev ]; then
+				continue
 			fi
+			i=0
+			while [ $i -ne 10 ]; do
+				((i++))
+				connect $dev $con
+				exitStatus=$?
+				if [ $exitStatus -ne 0 ]; then
+					echo "FAILED, RETRYING $exitStatus"|grep --color .\*
+				else
+					echo "SUCCESS $exitStatus"|grep --color .\*
+					exit
+				fi
+			done
 		done
 	done
-done
+fi
 
