created fixWifid and improved fixWifi

diff --git a/fixWifi b/fixWifi
--- a/fixWifi
+++ b/fixWifi
@@ -15,14 +15,23 @@ connect(){
 	return $?
 }
 
-build
-while true; do
-	connect
-	exitStatus=$?
-	if (( $exitStatus != 0 )); then
-		echo "FAILED, RETRYING $exitStatus"|grep --color .\*
-	else
-		echo "SUCCESS $exitStatus"|grep --color .\*
-		break
-	fi
-done
+connect
+exitStatus=$?
+if (( $exitStatus != 0 )); then
+	build
+	((i=0))
+	while true; do
+		((i++))
+		connect
+		exitStatus=$?
+		if (( $exitStatus != 0 )); then
+			echo "FAILED, RETRYING $exitStatus"|grep --color .\*
+		else
+			echo "SUCCESS $exitStatus"|grep --color .\*
+			break
+		fi
+		if ((i == 10)); then
+			break
+		fi
+	done
+fi
